type Contato {
    id: Int
    nome: String
    email: String
    telefone: String
}

input ContatoInput {
    id: Int
    nome: String
    email: String
    telefone: String
}

input FiltroInput {
    id: Int
    email: String
}

type Query {
    contato(id: Int!):Contato
    contatos: [Contato]
}

type Mutation {
    criarContato(data: ContatoInput):Contato
    atualizarContato(id: Int!, data: ContatoInput):Contato
    deletarContato(filtro: FiltroInput):Boolean
}